name: CI/CD — TechMarket Orders

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      env-vars:
        description: Variables de entorno CLAVE=VALOR separadas por comas para inyectar al contenedor
        required: false
        type: string
        default: "LOG_LEVEL=info"

jobs:
  build:
    name: Build
    uses: katalinaino/shared-workflows/.github/workflows/build-push-template.yaml@main
    with:
      image-name: demo-api
      image-tag: ${{ github.sha }}
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

  deploy:
    name: Deploy (Blue-Green)
    needs: build
    uses: katalinaino/shared-workflows/.github/workflows/deploy-bluegreen-template.yaml@main
    with:
      image-name: demo-api
      image-tag: ${{ github.sha }}
      k3s-server-public-ip: ${{ vars.K3S_SERVER_PUBLIC_IP }}
      k8s-namespace: default
      app-name: demo-api
      container-port: 3000
      health-path: /health
      env-vars: ${{ inputs.env-vars || 'LOG_LEVEL=info' }}
    secrets:
      EA2_SSH_PRIVATE_KEY: ${{ secrets.EA2_SSH_PRIVATE_KEY }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}