on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  usar-receta-compartida:
    uses: katalinaino/shared-workflows/.github/workflows/deploy-api.yaml@main
      image-name: demo-api
      image-tag: ${{ github.ref_name }}
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
